### ISSUE TITLE
Player data resets on dimension change

### ISSUE THREAD

**Issue by LemmaEOF** [raphydaphy/Crochet#2]

**Comment by raphydaphy** [comment]
oh I thought this was an arcane magic issue

**Comment by LemmaEOF** [comment]
nope, it's happening with skillcheck too, so it's something with crochet

**Comment by raphydaphy** [comment]
o dear. i will fix it today

**Comment by raphydaphy** [comment]
Fixed in Crochet 1.0.4 https://minecraft.curseforge.com/projects/crochet/files/2712636
