### ISSUE TITLE
Crash in 1.14.3

### ISSUE THREAD

**Issue by calloatti** [raphydaphy/Crochet#5]
https://paste.ee/p/s7ez1

**Loader**
Minecraft 1.14.3
[Fabric Loader 0.4.8+build.155](https://fabricmc.net)

**Mods**

**APIs/LIBs**
- [Crochet: Crochet-1.0.4.jar](https://www.curseforge.com/minecraft/mc-mods/crochet)
- [Fabric API: fabric-api-0.3.0+build.188.jar](https://www.curseforge.com/minecraft/mc-mods/fabric-api)

**Comment by calloatti** [comment]
I replaced fabric-networking-0.1.0+93af775a.jar inside  Crochet-1.0.4.jar with fabric-networking-v0-0.1.2+200eb5c2.jar from fabric-api-0.3.0+build.188.jar and edited the fabric.mod.json and it works, no crash.

**Comment by raphydaphy** [comment]
only took 2 months to fix https://www.curseforge.com/minecraft/mc-mods/crochet/files/2779995 so sorry
