### ISSUE TITLE
Please release a new build of Crochet with the fix from PR #4 :)

### ISSUE THREAD

**Issue by sargunv** [raphydaphy/Crochet#6]
The fabric-networking issue is causing players to complain about crashes with Beach Slimes. I'd love it if you released a new Crochet build with the fix from #4 (already merged) to mitigate the issue :)

**Comment by raphydaphy** [comment]
sorry for two month delay :) https://www.curseforge.com/minecraft/mc-mods/crochet/files/2779995

**Comment by sargunv** [comment]
Thanks for the release!

**Comment by raphydaphy** [comment]
wow i take two month to reply and you take four minutes, kind of feel bad now :cry: anyway no problem hope its still useful
